apiVersion: v1
kind: Pod
metadata:
  name: qos-nginx
  labels:
    env: 
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "200Mi"
        cpu: "700m"
      requests:
        memory: "200Mi"
        cpu: "700m"
  tolerations:
  - key: "rene"
    operator: "Equal"
    value: "awesome"
    effect: "NoSchedule"
  - key: "key1"
    operator: "Equal"
    value: "value1"
    effect: "NoSchedule"
  - key: "key2"
    operator: "Equal"
    value: "value2"
    effect: "NoExecute"
    tolerationSeconds: 3600
  - key: "company"
    operator: "Equal"
    value: "bestbuy"
    effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: group
            operator: In
            values:
            - three
          - key: disktype
            operator: In
            values:
            - ssd
          