apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  containers:
    - name: pvc-pod
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: pvcvol
  volumes:
    - name: pvcvol
      persistentVolumeClaim:
        claimName: pv-2claim