apiVersion: v1
kind: Pod
metadata:
  name: newsecrets
spec:
  containers:
  - name: newsecrets
    image: redis
    volumeMounts:
    - name: newsecrets
      mountPath: "/etc/newsecrets"
      readOnly: true
  volumes:
  - name: newsecrets
    secret:
      secretName: newsecrets